<?php

namespace YourVendor\ManagedJobs\Jobs;

use Carbon\Carbon;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Throwable;
use YourVendor\ManagedJobs\Enums\JobStatusEnum;
use YourVendor\ManagedJobs\Events\JobCompleted;
use YourVendor\ManagedJobs\Events\JobFailed;
use YourVendor\ManagedJobs\Events\JobProgressUpdated;
use YourVendor\ManagedJobs\Events\JobStarted;
use YourVendor\ManagedJobs\Models\ManagedJob;
use YourVendor\ManagedJobs\Models\ManagedJobFile;

abstract class BaseJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function __construct(
        public ManagedJob $jobExecution
    ) {
        $connection = config('managed-jobs.queue.connection');
        $queue      = config('managed-jobs.queue.name');

        if ($connection !== null) {
            $this->onConnection($connection);
        }

        if ($queue !== null) {
            $this->onQueue($queue);
        }
    }

    abstract public function handle(): void;

    /**
     * Automatic lifecycle middleware.
     *
     * On worker pickup  → status = RUNNING, started_at = now()
     * On handle() exit  → status = COMPLETED, finished_at = now(), fires JobCompleted
     * If already STOPPED → finished_at = now() (job exited early via isStopped())
     *
     * @return array<int, object>
     */
    public function middleware(): array
    {
        return [
            new class($this->jobExecution)
            {
                public function __construct(protected ManagedJob $jobExecution) {}

                public function handle($job, $next)
                {
                    $job->jobExecution->update([
                        'status'     => JobStatusEnum::RUNNING,
                        'started_at' => now(),
                    ]);

                    event(new JobStarted($job->jobExecution));

                    $result = $next($job);

                    $job->jobExecution->refresh();

                    if ($job->jobExecution->status === JobStatusEnum::RUNNING) {
                        $job->jobExecution->update([
                            'status'      => JobStatusEnum::COMPLETED,
                            'finished_at' => now(),
                        ]);

                        event(new JobCompleted($job->jobExecution));
                    } elseif ($job->jobExecution->status === JobStatusEnum::STOPPED) {
                        $job->jobExecution->update(['finished_at' => now()]);
                    }

                    return $result;
                }
            },
        ];
    }

    /**
     * Update the job progress percentage and message.
     * Fires JobProgressUpdated — broadcast or handle it however your app needs.
     */
    public function updateProgress(int $percent, string $message = ''): void
    {
        $this->jobExecution->update([
            'progress_percentage' => max(0, min(100, $percent)),
            'progress_message'    => $message,
        ]);

        event(new JobProgressUpdated($this->jobExecution));
    }

    /**
     * Check whether the job has been stopped externally.
     * Re-reads from DB — call this inside loops and return early if true.
     */
    public function isStopped(): bool
    {
        $this->jobExecution->refresh();

        return $this->jobExecution->status === JobStatusEnum::STOPPED;
    }

    /**
     * Persist a checkpoint. Retrieve it with getState() on retry.
     */
    public function saveState(array $state): void
    {
        $this->jobExecution->update(['state' => $state]);
    }

    /**
     * Retrieve the last saved checkpoint, or null if none exists.
     */
    public function getState(): ?array
    {
        return $this->jobExecution->state;
    }

    /**
     * Register a file generated by this job.
     *
     * @param  string       $path       Storage path.
     * @param  string       $filename   Display name for downloads.
     * @param  string       $mimeType   MIME type (e.g. 'text/csv').
     * @param  int          $sizeBytes  File size in bytes.
     * @param  Carbon|null  $expiresAt  Defaults to now() + config file_expiry_days.
     */
    public function addFile(
        string $path,
        string $filename,
        string $mimeType,
        int $sizeBytes,
        ?Carbon $expiresAt = null,
    ): ManagedJobFile {
        return ManagedJobFile::create([
            'job_id'     => $this->jobExecution->getKey(),
            'filename'   => $filename,
            'path'       => $path,
            'mime_type'  => $mimeType,
            'size_bytes' => $sizeBytes,
            'expires_at' => $expiresAt ?? now()->addDays((int) config('managed-jobs.file_expiry_days', 3)),
        ]);
    }

    /**
     * Called by Laravel when the job fails after exhausting retries.
     * Marks the job FAILED, stores the reason, and fires JobFailed.
     * Listen to JobFailed in your app to send notifications or trigger any side effect.
     */
    public function failed(Throwable $e): void
    {
        $this->jobExecution->update([
            'status'        => JobStatusEnum::FAILED,
            'failed_reason' => $e->getMessage(),
            'finished_at'   => now(),
        ]);

        event(new JobFailed($this->jobExecution));
    }
}
